"""
random module in Python generates pseudo-random numbers. It uses algorithms that are designed to produce sequences of numbers that appear 
random, but they are actually deterministic. 
The generated sequences are based on a starting point called the seed.

By default, the random module in Python uses the current system time as the seed, which helps to ensure that different runs of a program 
produce different sequences of pseudo-random numbers. However, it is also possible to set a specific seed value using the random.seed() 
function. Setting the seed to the same value will result in the same sequence of random numbers being generated.

Pseudo-random numbers are not truly random because they are generated by deterministic algorithms. If the seed and the algorithm used by 
the random module are known, it is theoretically possible to predict the sequence of numbers generated. 
"""

import random

# random.seed(20)
random_number = random.randint(0,10)

print(random_number)