import concurrent.futures
import time
import sys  
sys.path.insert(0, 'Multiprocessing_in_python\do_something.py')
from do_something import do_something as do_something

if __name__ == "__main__":
    start = time.perf_counter()
    with concurrent.futures.ProcessPoolExecutor() as executor:
        results = [executor.submit(do_something, 1) for _ in range(10)]
    
    for f in concurrent.futures.as_completed(results):
        print(f.result())
    finish = time.perf_counter()
    print(start)
    print(finish)
    print(f'Finished in {round(finish-start, 2)} second(s)')

#=======Output========#
# Sleeping 1 second(s)...
# Sleeping 1 second(s)...
# Sleeping 1 second(s)...
# Sleeping 1 second(s)...
# Sleeping 1 second(s)...
# Sleeping 1 second(s)...
# Sleeping 1 second(s)...
# Sleeping 1 second(s)...
# Sleeping 1 second(s)...
# Sleeping 1 second(s)...
# Done Sleeping...
# Done Sleeping...
# Done Sleeping...
# Done Sleeping...
# Done Sleeping...
# Done Sleeping...
# Done Sleeping...
# Done Sleeping...
# Done Sleeping...
# Done Sleeping...
# 157444.2356139
# 157445.6185311
# Finished in 1.38 second(s)