name: GitHub Actions Test

on:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Create and commit a file
        run: |
          echo "Hello, GitHub Actions!" > newfile.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add newfile.txt
          git commit -m "Add newfile.txt"
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
